trigger:
  branches:
    include:
      - main
  tags:
    include:
      - "*"

pr:
  branches:
    include:
      - "*"

resources:
  repositories:
    - repository: k8s_manifests
      type: github
      endpoint: grupoboticario
      name: grupoboticario/kubernetes-manifests
      ref: refs/tags/v0.1.3
    - repository: pipeline_templates
      type: github
      endpoint: grupoboticario
      name: grupoboticario/pipeline-templates
      ref: refs/tags/v0.1.19
    - repository: iac_scripts
      type: github
      endpoint: grupoboticario
      name: grupoboticario/iac-scripts
      ref: refs/tags/v0.1.8
  containers:
    - container: postgres
      image: postgres:11.5
      ports:
        - 5432:5432
      env:
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
        POSTGRES_DB: fake
        POSTGRES_USER: fake
        POSTGRES_PASSWORD: fake

variables:
  configuration.application.image: ""
  configuration.aws.credentials: ""
  configuration.sonar.serviceconnection: ""
  configuration.containerRegistry.buildTag: $(Build.BuildNumber)

pool:
  vmImage: "ubuntu-latest"

stages:
  - template: azure-pipelines/ci.yml
  - stage: Fortify
      displayName: Fortify Scan
      dependsOn: [ ]
      jobs:
        - template: /Fortify/SAST.yaml@pipeline_templates
          parameters:
            FortifyLanguageProfile: python
            FortifyPoetryExport: true
